version: '3.3'

services:
   db:
     image: mysql:5.7
     restart: always
     volumes:
       - ./db:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: wordpress:php7.4-apache
     restart: always
     ports:
       - "80:80"
     volumes:
       - ./web/plugins:/var/www/html/wp-content/plugins
       - ./web/themes:/var/www/html/wp-content/themes
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
